defaults:
  - task_config_base
  - actions:
    - stop
    - move_forward
    - turn_left
    - turn_right
  - measurements:
    - distance_to_goal
    - distance_to_goal_reward
    - multi_agent_nav_reward # for falcon
    - success 
    - did_multi_agents_collide 
    - num_steps 
    - top_down_map
    - spl
    - psc
    - stl
    - human_collision
    - human_future_trajectory # for falcon
  - lab_sensors:
    - localization_sensor 
    - human_num_sensor # for falcon
    - oracle_humanoid_future_trajectory # for falcon
  - _self_

type: MultiAgentPointNavTask-v0 # Nav-v0
end_on_success: True
reward_measure: "multi_agent_nav_reward"
success_measure: "spl"
success_reward: 10.0
slack_reward: -0.002
goal_sensor_uuid: pointgoal_with_gps_compass

