
defaults:
  - task_config_base
  # - actions:
  #   - stop
  #   - move_forward
  #   - turn_left
  #   - turn_right
  #   - look_up
  #   - look_down
  - measurements:
    - distance_to_goal
    - success
    - spl
    - soft_spl
    - distance_to_goal_reward
    - num_steps # 
    - did_multi_agents_collide
    - human_collision
    - human_future_trajectory
    # - top_down_map
    - multi_floor_map
    - psc
    - suc_psc
    - sec_1
    - sec_2
    - suc_sec_1
    - suc_sec_2
  - lab_sensors:
    - objectgoal_sensor
    - compass_sensor
    - gps_sensor
  - _self_

type: MultiAgentObjectNavTask-v0
end_on_success: True
reward_measure: "distance_to_goal_reward"
success_measure: "spl"


goal_sensor_uuid: objectgoal

measurements:
  distance_to_goal:
    distance_to: VIEW_POINTS
  success:
    success_distance: 0.1