# @package habitat.dataset
defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: ObjectNav-v1
split: train
data_path: data/datasets/objectnav/hm3d/debug_scene/{split}/{split}.json.gz
