# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: social_objectnav_task_multi_agent
  - /habitat/simulator/sensor_setups@habitat.simulator.agents.agent_0: spot_agent
  - /habitat/simulator/agents@habitat.simulator.agents.agent_0: spot
  - /habitat/simulator/sim_sensors@habitat_baselines.eval.extra_sim_sensors.third_rgb_sensor: third_rgb_sensor
  - /habitat/simulator/agents@habitat.simulator.agents.agent_1: human_1
  - /habitat/dataset/objectnav: hm3d_multi_v1
  - _self_

habitat:
  environment:
    max_episode_steps: 500
  simulator:
    type: RearrangeSim-v2
    agents_order:
      - agent_0
      - agent_1
    turn_angle: 30
    agents:
      agent_0:
        sim_sensors:
          jaw_rgb_sensor:
            width: 640
            height: 480
            hfov: 79
            position: [0, 0.88, 0]
          jaw_depth_sensor:
            width: 640
            height: 480
            hfov: 79
            min_depth: 0.5
            max_depth: 5.0
            position: [0, 0.88, 0]
        # height: 0.88
        # radius: 0.18
    kinematic_mode: True 
    habitat_sim_v0:
      gpu_device_id: 0
      allow_sliding: True # False, for human
      enable_physics: True  # for rearrangesim
